AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d3b3274b6c5d4aa
      KeyName: ec2key
      SecurityGroupIds:
        -sg-088f81b0e44645a05
        -sg-0e0327f7733f00a56
      SubnetId: subnet-0db61a20970a88ded