AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d3b3274b6c5d4aa
      KeyName: ec2key
      SecurityGroupIds:
        - sg-0ef8b22b494d4fb59
      SubnetId: subnet-0db61a20970a88ded