AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: String
  mySubnetID1: 
    Description: Subnet IDs
    Type: String
  ImageId:
    Description: Image ID
    Type: String
  EC2Name:
    Description: Ec2 Name
    Type: String  
Resources:
  WebInstance:
  InstanceType: t2.micro
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref myKeyPair
      SecurityGroupIds:
        - Fn::ImportValue: SG1
        - Fn::ImportValue: SG2
      SubnetId: !Ref mySubnetID1
      IamInstanceProfile:
        Fn::ImportValue: Instanceprofile
      Tags: 
        - Key: "Name"
          Value: !Ref EC2Name