AWSTemplateFormatVersion: "2010-09-09"
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09d3b3274b6c5d4aa
      KeyName: ec2key
      SecurityGroupIds:
        - Fn::ImportValue: SG1
        - Fn::ImportValue: SG2
      SubnetId: subnet-0db61a20970a88ded
      IamInstanceProfile:
        Fn::ImportValue: Instanceprofile