AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ec2role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref RootRole

Outputs:
  instanceprofile:
    Value: !Ref RootInstanceProfile
    Export: 
      Name: Instanceprofile
  role:
    Value: !Ref RootRole
    Export: 
      Name: Rolename
  roleARN:
    Value: !GetAtt RootRole.Arn
    Export: 
      Name: RolenameARN