AWSTemplateFormatVersion: "2010-09-09"
Resources:
  testsecuritygroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: test 1
      VpcId: vpc-03007d3b091b7a3a2

  testsecuritygroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: test 2
      VpcId: vpc-03007d3b091b7a3a2 
Outputs:
  securitygroup1:
    Value: !Ref testsecuritygroup1
    Export: 
      Name: SG1
  Securitygroup2:
    Value: !Ref testsecuritygroup2
    Export: 
      Name: SG2